# Site settings
title: PIEr
email: whomakepie@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Apple Pie.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  xxapp

permalink: /blog/:year/:month/:title
 
10 paginate: 12 
11 paginate_path: "blog/page:num" 

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["tables", "autolink"]